### PR TITLE
First cut at using testers2 parallel updates

### PR DESCRIPTION
**Pull request by chick**
For reference I have provided an adaptation of my earlier testers2 example.
I believe the testers2 approach gets around a rather difficult aspect of using ZIO
I still think the step() methods called at GridTest:46 and GridTest:61 will always be viewed
as a separate unrelated calls to advance the clock. This is not a fault of ZIO, but rather the way the backend interface works. Testers2 has done a lot of work to handle this problem of advancement of the clock when different threads are accessing the DUT. 
I did not understand the subtleties of runpar0, runpar1, and runpar2, and what they were supposed to be demonstrating. If you let me know what that is I can try and add those to this implementation.

### CODE REVIEW

**Comment by chick** [comment]
Merge this only if you want to. It brings in a dependency on testers2 which must be publishedLocal. But since you are relying on other snapshots here, you are probably ok with that.

**Comment by tampler** [comment]
Chick, I'll add you to the members. Pls create a separate branch "testers2" here and commit your changes. We'll have both branches at this moment for reference. Thank you!

**Comment by chick** [comment]
It appears that this depends on using the latest master of ucb-bar/chisel-testers2. The current snapshot is 4 commits behind master. I was able to get this to run by:
```
git clone https://github.com/ucb-bar/chisel-testers2.git
cd chisel-testers2
sbt publishLocal` in the cloned directory.
rm -rf ~/.ivy2/cache/edu.berkeley.cs/chisel-testers2_2.12/
cd ../twerk
sbt 'testOnly unit.GridTestUsingTesters2'
```
to get it to work.
I will check on the status of updating the testers2 snapshot. I should be fairly soon

**Comment by chick** [comment]
Aside from the build issue here I am wondering if the code approach looks reasonable. I believe it answers most of what I can determine as being desired by ZIO, but I am not entirely sure that I understand the specific goals.

**Review by tampler — COMMENTED** [review]
okay

**Pull request merged**
